services:
  postgres:
    container_name: 'audio-engineers-platform-db'
    image: 'postgres:14-alpine'
    ports:
      - '5432:5432'
    environment:
      POSTGRES_PASSWORD: 'postgres'
      POSTGRES_USER: 'postgres'
    volumes:
      - ./AudioEngineersPlatformBackend.Infrastructure/Config/Scripts/:/docker-entrypoint-initdb.d/ # Script for creating a Db and its user