name: ci.yml
on:
  pull_request:
    branches: [ main ]

jobs:
  # Adding random comment to add changes for merging test-actions. 
  build_and_push_to_dockerhub:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build and Docker image
        run: |
          docker build \
          -f Dockerfile \
          -t soundbest-api:latest .

      - name: Tag Docker image
        run: docker tag soundbest-api:latest ${{ secrets.DOCKER_HUB_USERNAME }}/soundbest-api:latest

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Push image to Dockerhub
        run: docker push ${{ secrets.DOCKER_HUB_USERNAME }}/soundbest-api:latest